//Ejercicio Granjera 1
console.log("Eliminar Pila");
console.log("Avanzar");
console.log("Eliminar Pila");
console.log("Avanzar");
console.log("Eliminar Pila");
console.log("Avanzar");
console.log("Eliminar Pila");
console.log("Girar a la Izquierda 90°");
console.log("Avanzar");
console.log("Eliminar Pila");
console.log("Avanzar");
console.log("Eliminar Pila");
console.log("Avanzar");
console.log("Eliminar Pila");
console.log("Avanzar");
console.log("Eliminar Pila");
console.log("Avanzar");
console.log("Eliminar Pila");
console.log("Ejercicio Completo");
